name: gps_maps
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.21
  cupertino_icons: ^0.1.2
  google_maps_webservice: ^0.0.14
  provider: ^3.1.0
  http: ^0.12.0+2
  geolocator: ^5.1.3
  get_it: ^3.0.0+1
  fluttertoast: ^3.1.3
  wakelock: ^0.1.3
  flutter_google_places: ^0.2.3
  mqtt_client: ^5.6.3
  after_layout: ^1.0.7+2
  flutter_polyline_points: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
  fonts:
    - family: SevenSegment
      fonts:
        - asset: fonts/Seven-Segment.ttf
